# Generated by Django 2.0 on 2020-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200212_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicmod',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='basicmod',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
