# Generated by Django 2.0 on 2020-02-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200212_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('category', models.CharField(max_length=250)),
            ],
        ),
    ]
