# Generated by Django 2.0 on 2020-02-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('firstname', models.CharField(max_length=100, unique=True)),
                ('lastname', models.CharField(max_length=100, unique=True)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=10)),
                ('email', models.EmailField(max_length=250)),
                ('fathername', models.CharField(max_length=100, unique=True)),
                ('joiningdate', models.DateField()),
                ('dob', models.DateField(blank=True)),
                ('spousename', models.CharField(max_length=100, unique=True)),
                ('currentresidencyaddress', models.CharField(max_length=100)),
                ('czip_code', models.CharField(max_length=20)),
                ('cstate', models.CharField(max_length=100)),
                ('ccountry', models.CharField(max_length=100)),
                ('permanentaddress', models.CharField(max_length=100)),
                ('pzip_code', models.CharField(max_length=20)),
                ('pstate', models.CharField(max_length=100)),
                ('pcountry', models.CharField(max_length=100)),
                ('personalcontactno', models.IntegerField(blank=True)),
                ('emergencycontactno', models.IntegerField(blank=True)),
                ('highesteducation', models.CharField(blank=True, max_length=250)),
                ('educationalinstitutename', models.CharField(blank=True, max_length=250)),
                ('yearofpassing', models.DateField(blank=True)),
                ('previousemployeename', models.CharField(blank=True, max_length=250)),
                ('previousempoyeefrom', models.DateField(blank=True)),
                ('previousempoyeeto', models.DateField(blank=True)),
                ('panno', models.CharField(blank=True, max_length=250)),
                ('bankedtailsforsalary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserImagesUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('userprofile', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
