# Generated by Django 3.0.3 on 2020-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='activeuser',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='employeeinfo',
            field=models.CharField(choices=[('F', 'Full Time'), ('P', 'Part Time'), ('O', 'Other')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
