# Generated by Django 2.0 on 2020-02-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20200225_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='emergency_contact_No',
            new_name='emergency_contact_no',
        ),
    ]
