# Generated by Django 2.0 on 2020-02-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20200225_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='agreeterms',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
