# Generated by Django 2.0 on 2020-02-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_auto_20200225_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(blank=True, max_length=250, null=True)),
                ('request_url', models.CharField(blank=True, max_length=250, null=True)),
                ('resp_code', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='joining_date',
            field=models.DateField(blank=True),
        ),
    ]
