# Generated by Django 2.0 on 2020-02-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_auto_20200226_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='banke_details_for_salary',
            new_name='bank_details_for_salary',
        ),
    ]
